app/cookies/models.py
from app.extensions.database import db, CRUDMixin


class Cookie(db.Model, CRUDMixin):
    id = db.Column(db.Integer, primary_key=True)
    slug = db.Column(db.String(80), unique=True)
    name = db.Column(db.String(80))
    price = db.Column(db.Numeric(10, 2))
    picture_url = db.Column(db.String(255))
    cookie_orders = db.relationship("CookieOrder", backref="cookie", lazy=True)

app/orders/models.py
from datetime import datetime, timezone
from app.extensions.database import db, CRUDMixin


class CookieOrder(db.Model, CRUDMixin):
    cookie_id = db.Column(db.Integer, db.ForeignKey("cookie.id"), primary_key=True)
    order_id = db.Column(db.Integer, db.ForeignKey("order.id"), primary_key=True)
    number_of_cookies = db.Column(db.Integer)


class Order(db.Model, CRUDMixin):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime, nullable=False, default=datetime.now(timezone.utc))
    address = db.relationship("Address", backref="order", uselist=False, lazy=True)
    cookie_orders = db.relationship("CookieOrder", backref="order", lazy=True)


class Address(db.Model, CRUDMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80))
    street = db.Column(db.String(80))
    city = db.Column(db.String(80))
    state = db.Column(db.String(80))
    zip = db.Column(db.String(80))
    country = db.Column(db.String(80))
    order_id = db.Column(db.Integer, db.ForeignKey("order.id"))

app/users/models.py
from app.extensions.database import db, CRUDMixin
from flask_login import UserMixin


class User(db.Model, CRUDMixin, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(128), index=True, unique=True)
    password = db.Column(db.String(1024))

app/api/__init__.py
from . import routes

app/api/routes.py
from os import environ
from flask import Blueprint, jsonify, request
from ..orders.models import Order
from .services.serialize_orders import serialize_orders

blueprint = Blueprint("api", __name__)


@blueprint.get("/api/v1/orders")
def get_orders():
    if environ.get("API_KEY") == request.headers.get("X-API-KEY"):
        orders = Order.query.all()
        return jsonify(serialize_orders(orders))
    else:
        return jsonify({"error": "INvalid API key"}), 401

app/app.py
from flask import Flask
from app.extensions.database import db, migrate
from app.extensions.authentication import login_manager
from . import cookies, simple_pages, orders, api, users


def create_app() -> Flask:
    app = Flask(__name__)
    app.config.from_object("app.config")

    register_extensions(app)
    register_blueprints(app)

    return app


def register_blueprints(app: Flask) -> None:
    app.register_blueprint(cookies.routes.blueprint)
    app.register_blueprint(simple_pages.routes.blueprint)
    app.register_blueprint(orders.routes.blueprint)
    app.register_blueprint(api.routes.blueprint)
    app.register_blueprint(users.routes.blueprint)


def register_extensions(app: Flask) -> None:
    db.init_app(app)
    migrate.init_app(app, db, compare_type=True)
    login_manager.init_app(app)

app/cookies/routes.py
from flask import Blueprint, render_template, request, current_app
from .models import Cookie

blueprint = Blueprint("cookies", __name__)


@blueprint.route("/cookies/<slug>")
def cookie(slug):
    cookie = Cookie.query.filter_by(slug=slug).first_or_404()

    return render_template("cookies/show.html", cookie=cookie)


@blueprint.route("/cookies")
def cookies():
    page_number = request.args.get("page", 1, type=int)
    cookies_pagination = Cookie.query.paginate(
        page=page_number, per_page=current_app.config["COOKIES_PER_PAGE"]
    )

    return render_template("cookies/index.html", cookies_pagination=cookies_pagination)


@blueprint.route("/run-seed")
def run_seed():
    if not Cookie.query.filter_by(slug="chocolate-chip").first():
        import app.scripts.seed

        return "Database seed completed!"
    else:
        return "Nothing to run."

app/orders/routes.py
from flask import Blueprint, render_template, request, current_app
from flask_login import login_required
from app.cookies.models import Cookie
from .services.create_order import create_order

blueprint = Blueprint("orders", __name__)


@blueprint.get("/orders/checkout")
@login_required
def get_checkout():
    cookies = Cookie.query.all()
    return render_template("orders/new.html", cookies=cookies)


@blueprint.post("/orders/checkout")
def post_checkout():
    try:
        cookies = Cookie.query.all()

        if not all(
            [
                request.form.get("name"),
                request.form.get("street"),
                request.form.get("city"),
                request.form.get("state"),
                request.form.get("zip"),
                request.form.get("country"),
            ]
        ):
            raise ValueError("Please fill out all address fields.")

        create_order(request.form, cookies)
        return render_template("orders/new.html", cookies=cookies)
    except Exception as error_message:
        error = (
            error_message
            or "An error occurred while processing your order. Please make sure to enter valid data."
        )
        current_app.logger.info(f"Error creating an order: {error}")

        return render_template(
            "orders/new.html",
            cookies=cookies,
            error=error,
        )

app/simple_pages/__init__.py
from . import routes

app/simple_pages/routes.py
from flask import Blueprint, render_template, redirect, url_for, send_file, current_app

blueprint = Blueprint("simple_pages", __name__)


@blueprint.route("/")
def index():
    return render_template("simple_pages/index.html")


@blueprint.route("/about")
def about():
    return "I like cookies"


@blueprint.route("/about-me")
def about_me():
    return redirect(url_for("simple_pages.about"))


@blueprint.route("/legal")
def legal():
    return "legal file"
    # return send_file("static/downloads/legal.txt", as_attachment=True)

app/users/__init__.py
from . import routes, models

app/users/routes.py
from flask import Blueprint, render_template, request, url_for, redirect, current_app
from flask_login import login_user, logout_user
from werkzeug.security import check_password_hash
from app.users.models import User
from .services.user_services import create_user, validate_new_user

blueprint = Blueprint("users", __name__)


@blueprint.get("/register")
def get_register():
    return render_template("users/register.html")


@blueprint.post("/register")
def post_register():
    try:
        validate_new_user(request.form)
        login_user(create_user(request.form))

        return redirect(url_for("cookies.cookies"))
    except Exception as error_message:
        current_app.logger.info(f"Error creating a user: {error_message}")

        return render_template(
            "users/register.html",
            error=error_message or "An error occurred while creating the user",
        )


@blueprint.get("/login")
def get_login():
    return render_template("users/login.html")


@blueprint.post("/login")
def post_login():
    try:
        user = User.query.filter_by(email=request.form.get("email")).first()
        if not user:
            raise ValueError("User not found")
        elif not check_password_hash(user.password, request.form.get("password")):
            raise ValueError("Password is incorrect")

        login_user(user)
        return redirect(url_for("cookies.cookies"))

    except Exception as error_message:
        error = error_message or "An error occurred while creating the user"
        return render_template("users/login.html", error=error)


@blueprint.get("/logout")
def logout():
    logout_user()
    return redirect(url_for("simple_pages.index"))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/main.css') }}"
    />
    {% endblock %}
  </head>
  <body>
    {% block body %}{% endblock %}
  </body>
  <footer>
    <hr />
    {% if current_user.is_authenticated %}
    <small>
      Logged in as {{ current_user.email }}.
      <a href="{{ url_for('users.logout') }}">Logout</a>
    </small>
    {% endif %}
  </footer>
</html>

app/templates/cookies/index.html
{% extends 'base.html' %} {% block title %}Cookies List{% endblock %} {% block
body %}
<h1>Available Cookies</h1>
{% for cookie in cookies_pagination.items %}
<div>
  <h2>{{ cookie.name }}</h2>
</div>
{% endfor %}
<p>Welcome to my cookie shop!</p>

<nav>
  {% if cookies_pagination.prev_num %}
  <a href="{{ url_for('cookies.cookies', page=cookies_pagination.prev_num) }}"
    >Previous Page</a
  >
  {% else %}
  <span>Previous Page</span>
  {% endif %}

  <span> - </span>

  {% if cookies_pagination.next_num %}
  <a href="{{ url_for('cookies.cookies', page=cookies_pagination.next_num) }}"
    >Next Page</a
  >
  {% else %}
  <span>Next Page</span>
  {% endif %}
</nav>
{% endblock %}

app/templates/cookies/show.html
{% extends 'base.html' %} {% block title %} {{cookie.name}} {% endblock %} {%
block body %}
<h1>{{ cookie.name }}</h1>
<p>{{ cookie.price }}</p>

<footer>
  <a href="/cookies">Back to all cookies</a>
</footer>
{% endblock %}

app/templates/orders/new.html
{% extends 'base.html' %} {% block title %}Cookieshop | Checkout{% endblock %}
{% block body %}

<h1>Checkout</h1>

<form method="POST">
  <h2>Your Order:</h2>
  <ul>
    {% for cookie in cookies %}
    <li>
      <label for="cookie_{{ cookie.id }}">{{ cookie.name }}</label>
      <input
        type="number"
        name="{{ cookie.slug }}"
        id="cookie_{{ cookie.id }}"
        min="0"
        value="0"
      />
    </li>
    {% endfor %}
  </ul>

  <h2>Your Address:</h2>
  <div>
    {% if error %}
    <p style="color: tomato">{{ error }}</p>
    {% endif %}jpy
    <label for="name">Full Name</label>
    <input type="text" name="name" id="name" placeholder="Jane Cookielover" />
  </div>
  <div>
    <label for="street">Street and Number:</label>
    <input
      type="text"
      name="street"
      id="street"
      placeholder="Sample Street 24"
    />
  </div>
  <div>
    <label for="city">City:</label>
    <input type="text" name="city" id="city" placeholder="Best Town" />
  </div>
  <div>
    <label for="state">State:</label>
    <input type="text" name="state" id="state" placeholder="Bakerstate" />
  </div>
  <div>
    <label for="zip">Zip:</label>
    <input type="text" name="zip" id="zip" placeholder="12345" />
  </div>
  <div>
    <label for="country">Country:</label>
    <input type="text" name="country" id="country" placeholder="Cookieland" />
  </div>
  <input type="submit" value="Submit Order" />
</form>

{% endblock %}

app/templates/simple_pages/index.html
{% extends 'base.html' %} {% block title %}Cookieshop{% endblock %} {% block
body %}
<h1>Hello World!</h1>

<p>Welcome to my cookie shop!</p>
{% endblock %}

app/templates/users/login.html
{% extends 'base.html' %} {% block title %}Cookieshop | Login{% endblock %} {%
block body %}
<h1>Login</h1>

<form method="POST">
  <div>
    <label for="email">Email</label>
    <input type="email" name="email" id="email" required />
  </div>

  <div>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" required />
  </div>

  {% if error %}
  <p style="color: tomato">{{ error }}</p>
  {% endif %}

  <input type="submit" value="Login" />
</form>
{% endblock %}

app/templates/users/register.html
{% extends 'base.html' %} {% block title %}Cookieshop | Register{% endblock %}
{% block body %}
<h1>Register</h1>

<form method="POST">
  <div>
    <label for="email">Email</label>
    <input type="email" name="email" id="email" required />
  </div>

  <div>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" required />
  </div>

  <div>
    <label for="password_confirmation">Password Confirmation</label>
    <input
      type="password"
      name="password_confirmation"
      id="password_confirmation"
      required
    />
  </div>

  {% if error %}
  <p style="color: tomato">{{ error }}</p>
  {% endif %}

  <input type="submit" value="Sign Up" />
</form>
{% endblock %}